"""add_kwh_field_to_fuel

Revision ID: e3fe50c91fd3
Revises: 473729386fd8
Create Date: 2025-05-28 21:16:10.572721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fe50c91fd3'
down_revision: Union[str, None] = '473729386fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Fuel_Info', sa.Column('kwh', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Fuel_Info', 'kwh')
    # ### end Alembic commands ###
