"""Rename vehicle_image_url to vehicle_image

Revision ID: ecf0149a2b64
Revises: 
Create Date: 2025-05-27 23:15:34.865474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecf0149a2b64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Fuel_Info_fuel_id'), 'Fuel_Info', ['fuel_id'], unique=False)
    op.create_index(op.f('ix_Maintenance_Info_maintenance_id'), 'Maintenance_Info', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_Reminders_Info_reminder_id'), 'Reminders_Info', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_Users_user_id'), 'Users', ['user_id'], unique=False)
    
    # Add new column
    op.add_column('Vehicles_Info', sa.Column('vehicle_image', sa.Text(), nullable=True))
    
    # Copy data from old column to new column
    op.execute("UPDATE Vehicles_Info SET vehicle_image = vehicle_image_url WHERE vehicle_image_url IS NOT NULL")
    
    op.alter_column('Vehicles_Info', 'year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_Vehicles_Info_vehicle_id'), 'Vehicles_Info', ['vehicle_id'], unique=False)
    
    # Drop old column after copying data
    op.drop_column('Vehicles_Info', 'vehicle_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vehicles_Info', sa.Column('vehicle_image_url', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_Vehicles_Info_vehicle_id'), table_name='Vehicles_Info')
    op.alter_column('Vehicles_Info', 'year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=False)
    op.drop_column('Vehicles_Info', 'vehicle_image')
    op.drop_index(op.f('ix_Users_user_id'), table_name='Users')
    op.drop_index(op.f('ix_Reminders_Info_reminder_id'), table_name='Reminders_Info')
    op.drop_index(op.f('ix_Maintenance_Info_maintenance_id'), table_name='Maintenance_Info')
    op.drop_index(op.f('ix_Fuel_Info_fuel_id'), table_name='Fuel_Info')
    # ### end Alembic commands ###
